apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"payload-cms","namespace":"application"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"payload-cms"}},"template":{"metadata":{"labels":{"app":"payload-cms"}},"spec":{"containers":[{"image":"nginx:alpine","name":"payload-cms","ports":[{"containerPort":80}],"volumeMounts":[{"mountPath":"/usr/share/nginx/html/index.html","name":"nginx-config","subPath":"index.html"}]}],"volumes":[{"configMap":{"items":[{"key":"index.html","path":"index.html"}],"name":"nginx-test-page"},"name":"nginx-config"}]}}}}
  creationTimestamp: "2025-03-08T18:21:14Z"
  generation: 4
  name: payload-cms
  namespace: application
  resourceVersion: "347927"
  uid: 22b59f21-d011-4e1c-a3c6-9d28f583350c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: payload-cms
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payload-cms
    spec:
      containers:
      - image: nginx:alpine
        imagePullPolicy: IfNotPresent
        name: payload-cms
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: nginx-conf
          subPath: nginx.conf
        - mountPath: /usr/share/nginx/html/index.html
          name: nginx-config
          subPath: index.html
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: nginx-config
        name: nginx-conf
      - configMap:
          defaultMode: 420
          items:
          - key: index.html
            path: index.html
          name: nginx-test-page
        name: nginx-config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-03-08T18:21:21Z"
    lastUpdateTime: "2025-03-08T18:21:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-03-08T19:01:14Z"
    lastUpdateTime: "2025-03-08T19:01:14Z"
    message: ReplicaSet "payload-cms-dbdfb8d7" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
