apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-test-page
  namespace: application
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Payload CMS Test Page</title>
    </head>
    <body>
        <h1>Payload CMS Test Page</h1>
        <p>This is a test page for Payload CMS.</p>
    </body>
    </html>
